import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = (base64: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64.split(',')[1],
      mimeType
    },
  };
};

export const partyfyImage = async (base64Image: string, mimeType: string): Promise<string> => {
  const imagePart = fileToGenerativePart(base64Image, mimeType);
  const prompt = `
    Your primary task is to edit this image to make it look like the person is holding a drink.
    The drink should be a realistic glass of beer, glass of whiskey, beer bottle, or whiskey bottle.
    Analyze the person's hand position carefully. You MUST place the drink in their hand if the pose is suitable for holding an object. Ensure the grip looks natural and convincing.
    ONLY if the hands are not visible or in a pose that makes holding a drink impossible, place it on a surface very close to them as a fallback.
    The added drink must seamlessly integrate with the image, matching the lighting, shadows, and perspective of the original photo.
    The goal is a high-quality, believable edit.
    IMPORTANT: Do not change the background. Do not change the person's face or body. Do not add any text or branding.
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        imagePart,
        { text: prompt },
      ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes: string = part.inlineData.data;
      const mimeType = part.inlineData.mimeType;
      return `data:${mimeType};base64,${base64ImageBytes}`;
    }
  }

  throw new Error("No image was generated by the API.");
};